name: 🐛 Bug Report
description: Report a bug to help us improve Neex
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
      placeholder: When I run `neex build`, it fails with...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: The build should complete successfully
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce
      placeholder: |
        1. Create a new project with `npm init`
        2. Run `neex build`
        3. See error
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Neex Version
      placeholder: "0.8.3"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Paste any relevant error messages
      render: shell
    validations:
      required: false
