name: 🚀 Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}

jobs:
  release:
    name: 🚀 Release
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup Node.js 22
        uses: actions/setup-node@v7
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v6

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-script: pnpm run build && pnpm release
          version-script: pnpm run version
          pr-base-branch: main
          commit-message: "chore: update versions"
          pr-title: "chore: update versions"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
